### ISSUE TITLE
Hi Bro, I want to know the cause of the error.

### ISSUE THREAD

**Issue by game9969** [leus/PesFacemod#2]
Hi, brother.

I wanted to modify the fpk file of Ronaldo (included in dlc6.0) made by Konami using the Modifire you made.

I set up Blender 2.80,
I added your add-on.

And I succeeded in importing the fpk file.

However, there is an error even if you export without any modification.

![image](https://user-images.githubusercontent.com/70663877/93032041-1f480000-f66a-11ea-9346-8c510843a20d.png)
This is a capture photo of the error message.

And is this add-on no longer updated?

and Does this add-on work on Blender 2.9?

**Comment by leus** [comment]
Try with the latest version - I'm no longer using slerp to export normals.
